---

- name: Creating user "{{ item.uusername }}"
  user: name={{ item.uusername }} password={{ item.upassword | password_hash('sha512') }}  shell=/bin/bash createhome=yes comment='create with ansible' #generate_ssh_key=yes
  with_items: '{{users}}'

- name: Expiring password for user "{{ item.uusername }}"
  shell: chage -d 30 "{{ item.uusername }}"
  with_items: '{{users}}'

- name: Sudoers | update sudoers file and validate
  lineinfile: "dest=/etc/sudoers
    insertafter=EOF
    line='{{ item.uusername }} ALL=(ALL) NOPASSWD: ALL'
    regexp='^{{ item.uusername }} .*'
    state=present"
  when: 'item.use_sudo == True'
  with_items: '{{users}}'

